### ISSUE TITLE
bug: panic on /metrics endpoint registration for multiple instances

### ISSUE THREAD

**Issue by drev74** [choria-io/asyncjobs#95]
Hello I'm using this lib in my code somehow like this:

```go
type QueueManager struct {
  Client *aj.Client
  Router *aj.Mux
}

func (m QueueManager) Run(ctx context.Context) error {
  return m.Client.Run(ctx, m.Router)
}

go p.Pong.Run(ctx)
```
When I run multiple tests, I'm getting the following error:
```bash
panic: http: multiple registrations for /metrics

goroutine 27 [running]:
net/http.(*ServeMux).Handle(0x121e8a0, {0xc066a9, 0x8}, {0xd8bc20?, 0xc000448c60})
        /usr/local/go/src/net/http/server.go:2478 +0x226
net/http.Handle(...)
        /usr/local/go/src/net/http/server.go:2521
github.com/choria-io/asyncjobs.(*Client).startPrometheus(0xc0001bd7d0)
        /home/bku/work/go/pkg/mod/github.com/choria-io/asyncjobs@v0.0.8-0.20220505123555-1d9f6ef7e6fb/client.go:137 +0xce
github.com/choria-io/asyncjobs.(*Client).Run(0xc0001bd7d0, {0xd8fbf8, 0xc00003a0c8}, 0xc0001ae358?)
        /home/bku/work/go/pkg/mod/github.com/choria-io/asyncjobs@v0.0.8-0.20220505123555-1d9f6ef7e6fb/client.go:81 +0x1bc
github.com/neurodyne-web-services/api-gateway/internal/worker.QueueManager.Run({0xc0001bd7d0?, 0xc0001bda70?}, {0xd8fbf8?, 0xc00003a0c8?})
```

This happens because of hardcoded `/metrics` endpoint, which reuses a common `http mux` for each instance, thus yielding in a panic.

Solution will follow in PR

**Comment by drev74** [comment]
@ripienaar

**Comment by ripienaar** [comment]
@drev74 I commented on the PR

**Comment by drev74** [comment]
resolved by a proper configuration
